Repository database-mesh/golang-sdk, pull requests merged in 2023-03, with the labels that each got.

#46 feat: add pkg random string
  pkg/random/string.go
Labels: size/M

#47 feat: add boltdb & encrypt & logger tools
  go.mod
  go.sum
  pkg/boltdb/boltdb_suite_test.go
  pkg/boltdb/store.go
  pkg/boltdb/store_test.go
  pkg/encrypt/encrypt.go
  pkg/logger/logger.go
  pkg/logger/logger_suite_test.go
  pkg/logger/logger_test.go
  pkg/logger/logger_var.go
Labels: enhancement, size/XL

#48 feat: add publicAccessible to DatabaseClassSpec
  config/crd/bases/core.database-mesh.io_databaseclasses.yaml
  kubernetes/api/v1alpha1/databaseclass.go
Labels: size/S

#49 feat: add snapshot
  aws/client/rds/cluster.go
  aws/client/rds/instance.go
Labels: size/M

#51 fix: fix AWS Rds client
  aws/client/rds/rds.go
Labels: size/S

#52 feat: update DatabaseClass Spec
  config/crd/bases/core.database-mesh.io_databaseclasses.yaml
  kubernetes/api/v1alpha1/databaseclass.go
  kubernetes/api/v1alpha1/zz_generated.deepcopy.go
Labels: size/M
