Repository database-mesh/golang-sdk, pull requests merged in 2023-06, with the labels that each got.

#61 add cluster status and add DescribeInstanceSnapshot
  aws/client/rds/cluster.go
  aws/client/rds/instance.go
  aws/client/rds/instance_test.go
  aws/client/rds/rds.go
Labels: size/M

#62 typo: update cluster status name
  aws/client/rds/cluster.go
Labels: size/M

#63 feat: aws rds instance add SetFilter and DescribeAll
  aws/client/rds/instance.go
  aws/client/rds/instance_test.go
Labels: size/M

#64 refactor: refactor create and delete aurora
  aws/client/rds/aurora.go
  aws/client/rds/aurora_test.go
Labels: size/M

#65 fix: returns err when describe/delete aurora and aurora is not exist
  aws/client/rds/aurora.go
Labels: size/XS

#66 feat: add SetDBName for aurora
  aws/client/rds/aurora.go
Labels: size/XS

#67 chore: update cluster status type
  aws/client/rds/aurora.go
  aws/client/rds/cluster.go
  aws/client/rds/cluster_test.go
  aws/client/rds/rds_suite_test.go
Labels: size/L

#68 feat: aws cluster add SetSkipFinalSnapshot
  aws/client/rds/cluster.go
  aws/client/rds/cluster_test.go
Labels: size/M

#69 feat: add SetFinalSnapshot and handler notfound error of aws rds cluster
  aws/client/rds/cluster.go
  aws/client/rds/cluster_test.go
Labels: size/M

#70 feat: add set and get bucket/object func and tests
  aws/client/s3/bucket.go
  aws/client/s3/bucket_test.go
  aws/client/s3/object.go
  aws/client/s3/object_test.go
  aws/client/s3/s3.go
  aws/client/s3/s3_suite_test.go
Labels: size/L

#71 add create/get snapshot interfaces
  aws/client/rds/aurora.go
  aws/client/rds/aurora_test.go
  aws/client/rds/cluster.go
  aws/client/rds/rds.go
Labels: size/L

#72 update instance snapshot struct
  aws/client/rds/aurora.go
  aws/client/rds/cluster.go
  aws/client/rds/instance.go
Labels: size/M

#73 feat: add delete folder func
  aws/client/s3/object.go
  aws/client/s3/object_test.go
Labels: size/M

#75 feat: add funcs of restore from snapshot
  aws/client/rds/aurora.go
  aws/client/rds/aurora_test.go
  aws/client/rds/cluster.go
  aws/client/rds/cluster_test.go
  aws/client/rds/instance.go
  aws/client/rds/instance_test.go
  aws/client/rds/rds.go
Labels: size/L

#76 chore(aws): rename aws credential keys
  aws/aws.go
  aws/client/rds/aurora_test.go
  aws/client/rds/cluster_test.go
  aws/client/rds/instance_test.go
  aws/client/rds/rds_suite_test.go
  aws/client/rds/rds_test.go
  aws/client/s3/bucket_test.go
  aws/client/s3/object_test.go
  aws/client/s3/s3_suite_test.go
Labels: size/L

#77 aws rds support pitr
  aws/client/rds/aurora.go
  aws/client/rds/aurora_test.go
  aws/client/rds/cluster.go
  aws/client/rds/cluster_test.go
  aws/client/rds/instance.go
  aws/client/rds/instance_test.go
Labels: size/L
